---

- hosts: "maxscale"
  become: yes
  become_user: root
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  tasks:

  - name: "Copy MaxScale Static Config"
    template:
      src: ../templates/maxscale.cnf.j2
      dest: /etc/maxscale.cnf

  - name: "Restarting MaxScale"
    systemd:
      state: restarted
      name: maxscale

  - name: "Clearing MaxScale"
    uri:
      url: http://127.0.0.1:8989/v1/{{ item.resource }}/{{ item.name }}
      method: DELETE
      user: admin
      password: mariadb
      status_code: 204,404
    loop:
      - { resource: monitors, name: 'mdb_monitor?force=yes' }
      - { resource: services, name: 'mdb_service?force=yes' }
      - { resource: listeners, name: mdb_listener }
      - { resource: servers, name: mdb1 }
      - { resource: servers, name: mdb2 }
      - { resource: servers, name: mdb3 }
    no_log: true

  - name: "Adding Servers To MaxScale"
    uri:
      url: http://127.0.0.1:8989/v1/servers
      method: POST
      body_format: json
      body: {"data":{"id":"{{ item.name }}","type":"servers","attributes":{"parameters":{"address":"{{ item.host }}","protocol":"MariaDBBackend"}}}}
      user: admin
      password: mariadb
      status_code: 204
    loop:
       - {"name": "mdb1", "host": "{{ mdb1_private }}"}
       - {"name": "mdb2", "host": "{{ mdb2_private }}"}
       - {"name": "mdb3", "host": "{{ mdb3_private }}"}
    no_log: true

  - name: "Adding Monitor To MaxScale"
    uri:
      url: http://127.0.0.1:8989/v1/monitors
      method: POST
      body_format: json
      body: {"data":{"id":"mdb_monitor","type":"monitors","attributes":{"module":"mariadbmon","parameters":{"user":"{{ maxscale_user }}","password":"{{ maxscale_pass }}","replication_user":"{{ repli_user}}","replication_password":"{{ repli_pass }}","cooperative_monitoring_locks":"majority_of_running","enforce_read_only_slaves":true,"auto_failover":true,"auto_rejoin":true}},"relationships":{"servers":{"data":[{"id":"mdb1","type":"servers"},{"id":"mdb2","type":"servers"},{"id":"mdb3","type":"servers"}]}}}}
      user: admin
      password: mariadb
      status_code: 204
    no_log: true

  - name: "Adding Service To MaxScale"
    uri:
      url: http://127.0.0.1:8989/v1/services
      method: POST
      body_format: json
      body: {"data":{"id":"mdb_service","type":"services","attributes":{"router":"readwritesplit","parameters":{"user":"{{ maxscale_user }}","password":"{{ maxscale_pass }}","master_accept_reads":true}},"relationships":{"servers":{"data":[{"id":"mdb1","type":"servers"},{"id":"mdb2","type":"servers"},{"id":"mdb3","type":"servers"}]}}}}
      user: admin
      password: mariadb
      status_code: 204
    no_log: true

  - name: "Adding Listener To MaxScale"
    uri:
      url: http://127.0.0.1:8989/v1/listeners
      method: POST
      body_format: json
      body: {"data":{"id":"mdb_listener","type":"listeners","attributes":{"parameters":{"protocol":"MariaDBClient","port":3306}},"relationships":{"services":{"data":[{"id":"mdb_service","type":"services"}]}}}}
      user: admin
      password: mariadb
      status_code: 204
    no_log: true
